Add type annotations for pybind11 extension
r-barnes/faster-unmixer pull request #10
Opened 2022-10-28 22:20 UTC by r-barnes

2022-10-30 22:59 UTC, r-barnes commented
This differs from `main` if the regularizers are enabled on both. I'm not sure if that means there's a mistake on main or a mistake on this branch :-(

2022-10-31 12:16 UTC, AlexLipp requested changes
Can we update the geospatial output (currently `labels.tif`) to map the sample string to the subcatchment areas? This current change means the the `get_unique_upstream_areas` function is not working correctly as it relied on a particular ordering of then nodes (which was in any case undesirable). Mapping areas by the strings makes this easier. Not sure if `.tif` allows for strings though so this might need to be a different raster file format. Alternatively, a key could be made that maps the node numbers used in `labels.tif` onto sample numbers.

2022-11-11 21:38 UTC, r-barnes commented on src/faster-unmixer.cpp
> +
I believe I've fixed this now.

2022-11-17 14:36 UTC, AlexLipp approved these changes
I checked the results of these changes locally and the matching between areas and sample sites is fixed, producing sensible outputs again.

2022-11-18 02:05 UTC, merged