Add regularization by penalising relative deviations from mean
r-barnes/faster-unmixer pull request #27
Opened 2022-12-01 15:21 UTC by AlexLipp

We currently regularise by penalising the *roughness* of the proposed solution, considering adjacent nodes. However, this considers only absolute difference between nodes when relative deviations are desired. This current method produces results which thus allow for significant overfitting of low-magnitude observations (i.e., orders of magnitude below one) which is undesirable for fitting (for example) trace element concentrations. An example of these undesirable outputs are shown here: 
![old_regularization](https://user-images.githubusercontent.com/10188895/205090502-b5c34f28-09b3-4fdc-8aa7-649ebccb4865.png)

In this PR, I instead penalise *relative* deviations of each variable from the mean of all observations. This permits slightly 'rougher' solutions, but inspecting the results, the results are elsewise much better conditioned. Specifically, no longer do we see outputs spuriously spanning many orders of magnitude below, as shown in the example below which is same as example above but with new regularization method: 

![new_regularization](https://user-images.githubusercontent.com/10188895/205090417-d6ff0090-98bf-44e0-9782-7010b33ed405.png)

This PR removes the need for an adjacency matrix which also simplifies the code.

2022-12-01 15:22 UTC, AlexLipp commented
If we decide to pursue this in we should change `obs_mean` to be the *geometric* mean of the data not the arithmetic mean as it currently is.

2022-12-08 16:45 UTC, r-barnes commented
I'm okay going with this for now as I don't have better ideas yet of how to combine log-ratio regularization with the log-ratio primary terms. If we decide to stick with it for the long-term, I should probably go back and remove the sample adjacency/border length code.

2022-12-08 17:13 UTC, AlexLipp commented
Agreed on this. The specific attachment to smoothness as opposed to model size is a legacy from previous ways of solving in any case.

2022-12-08 17:28 UTC, r-barnes requested changes

2022-12-08 17:53 UTC, r-barnes commented
@AlexLipp : Could you also rebase to fix the merge conflict?

2022-12-08 17:55 UTC, AlexLipp commented on geochem_inverse_optimize.py
> +            self._regularizer_terms.append(cp.maximum(concen, cp.inv_pos(concen)))
Although I will update this mean value to be the geometric mean.

2022-12-09 14:40 UTC, AlexLipp commented
@r-barnes I've incorporated the suggested changes and rebased to main

2023-01-16 18:00 UTC, r-barnes approved these changes

2023-01-16 18:01 UTC, merged